# Generated by Django 4.2 on 2023-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.ImageField(null=True, upload_to='static/app_for_getting_photo_url/app_content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
