# Generated by Django 4.2 on 2023-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_getting_photo_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcontent',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
