# Generated by Django 4.2 on 2023-04-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_getting_photo_url', '0002_appcontent_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppContent',
            new_name='AppContentByProgrammer',
        ),
    ]
