# Generated by Django 4.2.1 on 2023-05-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comments_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='comments_videos')),
                ('gif', models.FileField(blank=True, null=True, upload_to='comments_gif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
