# Generated by Django 4.2 on 2023-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='gif',
            field=models.FileField(blank=True, upload_to='media/comments_gif'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/comments_images'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='video',
            field=models.FileField(blank=True, upload_to='media/comments_videos'),
        ),
    ]
