# Generated by Django 4.2.1 on 2023-06-17 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_followin_users_followingusers_following_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followingusers',
            name='following_users',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='following+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FollowersUsers',
        ),
        migrations.DeleteModel(
            name='FollowingUsers',
        ),
    ]
