# Generated by Django 4.2 on 2023-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('image', models.ImageField(blank=True, upload_to='media/post_images')),
                ('video', models.FileField(blank=True, upload_to='media/post_videos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='tags.tags')),
            ],
        ),
    ]
