# Generated by Django 4.2 on 2023-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_wall', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gif',
            field=models.FileField(blank=True, upload_to='media/post_gif'),
        ),
    ]
