# Generated by Django 4.2 on 2023-04-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_wall', '0004_alter_post_gif_alter_post_image_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='post_gif'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos'),
        ),
    ]
